REGISTER_COMMAND = 0xFD
REGISTER_COMMAND_WRITE_LOCK = 0xFE
REGISTER_INTERRUPT_MASK = 0xF0
REGISTER_INTERRUPT_STATUS = 0xF1
REGISTER_ID = 0xFC # only used by later devices

REGISTER_ID_VALUE_IS31FL3733 = 0

PAGE_LED_ON_OFF = 0x00
PAGE_LED_PWM = 0x01
PAGE_LED_AUTO_BREATH = 0x02
PAGE_FUNCTION = 0x03

COMMAND_WRITE_LOCK_DISABLE_ONCE = 0xC5
COMMAND_WRITE_LOCK_ENABLED = 0x00

REGISTER_FUNCTION_CONFIGURATION = 0x00

REGISTER_FUNCTION_CONFIGURATION_SYNC_CLOCK_MASTER = 64
REGISTER_FUNCTION_CONFIGURATION_SYNC_CLOCK_SLAVE = 128
REGISTER_FUNCTION_CONFIGURATION_SYNC_CLOCK_SINGLE = 0
REGISTER_FUNCTION_CONFIGURATION_TRIGGER_OPEN_SHORT_DETECTION = 4
REGISTER_FUNCTION_CONFIGURATION_BREATHING_ENABLE = 2
REGISTER_FUNCTION_CONFIGURATION_SOFTWARE_SHUTDOWN = 1


REGISTER_FUNCTION_CURRENT_CONTROL = 0x01
# all the auto breathing stuff here TK TK TODO
REGISTER_FUNCTION_TIME_UPDATE = 0x0E
REGISTER_FUNCTION_PULL_UP_RESISTOR = 0x0F
REGISTER_FUNCTION_PULL_DOWN_RESISTOR = 0x10
REGISTER_FUNCTION_RESET = 0x11


RESISTOR_NONE = 0
RESISTOR_500 = 1
RESISTOR_1K = 2
RESISTOR_2K = 3
RESISTOR_4K = 4
RESISTOR_8K = 5
RESISTOR_16K = 6
RESISTOR_32K = 7
